load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hexapod",
    srcs = ["main.cpp"],
    deps = [
        "//firmware/lib/kinematics:leg",
        "//firmware/lib/tools:debug",
        "@arduino_core",
    ],
)

genrule(
    name = "hex",
    srcs = [":hexapod"],
    outs = ["hexapod.hex"],
    cmd = "avr-objcopy -O ihex -R .eeprom $< $@",
)
