load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "leg",
    srcs = ["leg.cc"],
    hdrs = [
        "coordinate.h",
        "i_servo.h",
        "leg.h",
    ],
    includes = ["."],
)

cc_library(
    name = "trajectory_planner",
    srcs = ["trajectory_planner.cc"],
    hdrs = [
        "trajectory_planner.h",
    ],
    includes = ["."],
    deps = [
        "leg",
        "//firmware/lib/math:hexapod_math",
    ],
)

cc_library(
    name = "hardware",
    hdrs = [
        "hardware_servo.h",
    ],
    includes = ["."],
    deps = [
        "@arduino_core",
        "@arduino_servo",
    ],
)
