package(default_visibility = ["//visibility:public"])

# ==========================================
# 1. PLATFORM DEFINITIONS
# ==========================================
constraint_setting(name = "cpu")

constraint_value(
    name = "avr",
    constraint_setting = ":cpu",
)

platform(
    name = "avr_platform",
    constraint_values = [
        "@platforms//os:none",  # Bare metal
        ":avr",  # The constraint we just defined above
    ],
)

# ==========================================
# 2. TOOLCHAIN REGISTRATION
# ==========================================
toolchain(
    name = "avr_toolchain",
    exec_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    target_compatible_with = [
        ":avr",  # Tells the toolchain to trigger when the :avr constraint is requested
    ],
    toolchain = "@avr_toolchain_linux//:avr_cc_toolchain",
    toolchain_type = "@rules_cc//cc:toolchain_type",
)
